export default function Main() {
    return (
        <main style={{ background: "white" }}>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>

            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quod molestiae repudiandae maiores fuga aut a eveniet unde obcaecati, ratione error sapiente neque quibusdam quasi consequuntur voluptatem totam dolores praesentium.</div>
        </main>
    )

}